# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4ac4c1338355655a9c2eafb031cdfd2d8ce09173c5428004e4b62aca98ebf8c748b26b331ec2c7c0b7eb170930b3ba8406ab876cb801d5dff58f44ccd35473f

test:
  secret_key_base: 4885d9317413fccfd5b87c69575598eb6d9cfede15e28c2beeedee0f8ba64c5927aed8d5a2b190329d913ae514de2b07e551f48650d6f7dc0574431fa99d6d66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
